CREATE TABLE GUEST
(

    GUEST_ID INTEGER ,
	FIRST_NAME VARCHAR2(15) NOT NULL,
	LAST_NAME VARCHAR2(15),
	ADDRESS VARCHAR2(30) NOT NULL,
	CONTACT_NO CHAR(15),
	TOTAL_PERSON INTEGER,
	PASSPORT_NO varchar2(30),
	NID CHAR(20),
	

	PRIMARY KEY (GUEST_ID),

	CHECK(PASSPORT_NO IS NOT NULL OR NID IS NOT NULL)
	
	
);
CREATE TABLE BOOKING
(
   DATE_FROM DATE NOT NULL,
   DATE_TO DATE ,
   BOOKING_ID INTEGER,
   
   BOOKED_BY_GUEST INTEGER,


	 PRIMARY KEY(BOOKING_ID),
	 FOREIGN KEY(BOOKED_BY_GUEST) REFERENCES GUEST(GUEST_ID)
);
CREATE TABLE EMPLOYEE
(
	EMPLOYEE_ID INTEGER,
	EMAIL VARCHAR2(80),
	CONTACT_NO CHAR(15),
	EMPLOYEE_FIRST_NAME VARCHAR2(15),
	EMPLOYEE_LAST_NAME VARCHAR2(15),
	DEPARTMENT CHAR(20),
	DESIGNATION CHAR(20),


	PRIMARY KEY(EMPLOYEE_ID)
);

CREATE TABLE ROOM
(
	ROOM_NO INTEGER,
	FLOOR_NO INTEGER,
	STATUS CHAR(15),
	ROOM_COST FLOAT,
	WI_FI CHAR(15),
	AIR_CONDITIONER CHAR(15),
	SPECALITY VARCHAR2(50),
	CAPACITY INTEGER,
	ROOM_BOOKING_ID INTEGER,
	ROOM_EMPLOYEE_ID INTEGER,
	PAY_STATE CHAR(15),
	
	PRIMARY KEY(ROOM_NO),
	FOREIGN KEY(ROOM_BOOKING_ID) REFERENCES BOOKING(BOOKING_ID),
	FOREIGN KEY(ROOM_EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);


CREATE TABLE BILL_AUTHORIZATION
(
	BILL_EMPLOYEE_ID INTEGER,
	BILL_DESIGNATION CHAR(20),
	BILL_AUTHORIZATION CHAR(20),

	PRIMARY KEY(BILL_EMPLOYEE_ID),
	FOREIGN KEY(BILL_EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
	CHECK (BILL_DESIGNATION = 'ACCOUNTANT')
	
	
);
CREATE TABLE BILL
(	
	BILL_ID INTEGER,
	REFUNDABLE CHAR(15),
	BILL_DATE DATE,
	AMOUNT FLOAT,
	EMPLOYEE_ID INTEGER,
	GUEST_ID INTEGER,
	PAYMENT_METHOD CHAR (20),
  
	PRIMARY KEY(BILL_ID),
	FOREIGN KEY(GUEST_ID) REFERENCES GUEST(GUEST_ID),
	FOREIGN KEY(EMPLOYEE_ID) REFERENCES BILL_AUTHORIZATION(BILL_EMPLOYEE_ID)
	
 

);




CREATE TABLE FACILITY
(
	FACILITY_ID INTEGER ,
	PRICE FLOAT,
	PAY_STATE CHAR(20),
	FACILITY_BOOKING_ID INTEGER,
	ASSIGNED_EMPLOYEE_ID INTEGER,
	PRIMARY KEY(FACILITY_ID),
	FOREIGN KEY(FACILITY_BOOKING_ID) REFERENCES BOOKING(BOOKING_ID),
	FOREIGN KEY(ASSIGNED_EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID)
);




CREATE TABLE CHECK_IN_CONFIRMATION
(
	CHECK_IN_TIME DATE,
	CHECK_IN_BOOKING_ID ,
	CHECK_IN_EMPLOYEE_ID INTEGER,
	CHECK_IN_ROOM_NO INTEGER,
PRIMARY KEY(CHECK_IN_BOOKING_ID,CHECK_IN_EMPLOYEE_ID,CHECK_IN_ROOM_NO),
FOREIGN KEY(CHECK_IN_BOOKING_ID) REFERENCES BOOKING(BOOKING_ID),
FOREIGN KEY(CHECK_IN_EMPLOYEE_ID) REFERENCES EMPLOYEE(EMPLOYEE_ID),
FOREIGN KEY(CHECK_IN_ROOM_NO) REFERENCES ROOM(ROOM_NO)

);


CREATE TABLE DISCOUNT
(
	DISCOUNT_RATE FLOAT,
	DISCOUNT_MEMBER_TYPE CHAR(20),
	DISCOUNT_FACILITY_ID INTEGER,
PRIMARY KEY(DISCOUNT_MEMBER_TYPE),
FOREIGN KEY(DISCOUNT_FACILITY_ID) REFERENCES FACILITY(FACILITY_ID)
);

CREATE TABLE CLUB_MEMBER
(
	MEMBER_TYPE CHAR(20),
	MEMBER_ID INTEGER,
	MEMBER_GUEST_ID INTEGER,

	PRIMARY KEY(MEMBER_GUEST_ID),
FOREIGN KEY(MEMBER_GUEST_ID) REFERENCES GUEST(GUEST_ID)
);

CREATE SEQUENCE GUEST_ID_SEQ
INCREMENT BY 1
START WITH 10001
MAXVALUE 99999999999
NOCYCLE ;

CREATE SEQUENCE BOOKING_ID_SEQ
INCREMENT BY 1
START WITH 1000101
MAXVALUE 99999999999
NOCYCLE ;


CREATE SEQUENCE EMPLOYEE_ID_SEQ
INCREMENT BY 1
START WITH 110101
MAXVALUE 99999999999
NOCYCLE ;

CREATE SEQUENCE BILL_ID_SEQ
INCREMENT BY 1
START WITH 9999
MAXVALUE 99999999999
NOCYCLE ;

CREATE SEQUENCE FACILITY_ID_SEQ
INCREMENT BY 1
START WITH 199991
MAXVALUE 99999999999
NOCYCLE ;


CREATE OR REPLACE 
FUNCTION INSERT_BOOKING(DF IN VARCHAR2,DT in VARCHAR2,GID NUMBER ) 
RETURN NUMBER
IS
BID NUMBER;
BEGIN
	-- routine body goes here, e.g.
	-- DBMS_OUTPUT.PUT_LINE('Navicat for Oracle');
	BID:=BOOKING_ID_SEQ.NEXTVAL;
	INSERT INTO BOOKING (DATE_FROM,DATE_TO,BOOKING_ID,BOOKED_BY_GUEST) VALUES(TO_DATE(DF,'DD/MM/YYYY'),TO_DATE(DT,'DD/MM/YYYY'),BID,GID);
	
	RETURN BID;
END;

CREATE OR REPLACE 
FUNCTION INSERT_GUEST(FNAME IN VARCHAR2,LNAME IN VARCHAR2,G_ADDRESS IN VARCHAR2,CON IN CHAR,TP IN NUMBER,PASSPORT IN VARCHAR2,NID_NO IN VARCHAR2)
 RETURN NUMBER
IS
GID NUMBER;
BEGIN
-- routine body goes here, e.g.
-- DBMS_OUTPUT.PUT_LINE('Navicat for Oracle');
GID:=GUEST_ID_SEQ.NEXTVAL;
INSERT INTO GUEST (GUEST_ID,FIRST_NAME,LAST_NAME,ADDRESS,CONTACT_NO,TOTAL_PERSON,PASSPORT_NO,NID)VALUES(GID,FNAME,LNAME,G_ADDRESS,CON,TP,PASSPORT,NID_NO);
RETURN GID;
END;


DROP TABLE CLUB_MEMBER;
DROP TABLE DISCOUNT;
DROP TABLE CHECK_IN_CONFIRMATION;
DROP TABLE ROOM ;
DROP TABLE BILL;
DROP TABLE BILL_AUTHORIZATION;
DROP TABLE FACILITY;
DROP TABLE EMPLOYEE;
DROP TABLE BOOKING;
DROP TABLE GUEST;



